# Generated by Django 5.0.2 on 2024-12-12 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("xero_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="xerotenant",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "user"), name="unique_tenant_user"
            ),
        ),
    ]
